"""added columns author_id and book_id from books_authors

Revision ID: 2162685ac8b9
Revises: a53316d53b9d
Create Date: 2022-05-06 03:00:33.838614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2162685ac8b9'
down_revision = 'a53316d53b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_authors', sa.Column('author_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('books_authors', sa.Column('book_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'books_authors', 'authors', ['author_id'], ['author_id'])
    op.create_foreign_key(None, 'books_authors', 'books', ['book_id'], ['book_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books_authors', type_='foreignkey')
    op.drop_constraint(None, 'books_authors', type_='foreignkey')
    op.drop_column('books_authors', 'book_id')
    op.drop_column('books_authors', 'author_id')
    # ### end Alembic commands ###
