"""removed columns genre_id and book_id from books_genres

Revision ID: 23cafc0185e9
Revises: 2162685ac8b9
Create Date: 2022-05-06 03:14:04.715132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23cafc0185e9'
down_revision = '2162685ac8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_genres_genre_id_fkey', 'books_genres', type_='foreignkey')
    op.drop_constraint('books_genres_book_id_fkey', 'books_genres', type_='foreignkey')
    op.drop_column('books_genres', 'book_id')
    op.drop_column('books_genres', 'genre_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_genres', sa.Column('genre_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('books_genres', sa.Column('book_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('books_genres_book_id_fkey', 'books_genres', 'books', ['book_id'], ['book_id'])
    op.create_foreign_key('books_genres_genre_id_fkey', 'books_genres', 'genres', ['genre_id'], ['genre_id'])
    # ### end Alembic commands ###
