"""change columns name reader_book_id to review_id

Revision ID: 279e1bc9bff4
Revises: 15a894b3b1ab
Create Date: 2022-05-05 10:13:38.761034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '279e1bc9bff4'
down_revision = '15a894b3b1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.add_column('reviews', sa.Column('review_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_column('reviews', 'reader_book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reader_book_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'review_id')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=511), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=511), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    # ### end Alembic commands ###
