"""removed column reciever_id

Revision ID: 32588dc02189
Revises: 08a369aa4314
Create Date: 2022-04-30 23:05:58.965467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32588dc02189'
down_revision = '08a369aa4314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.drop_constraint('messages_reciever_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'reciever_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reciever_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('messages_reciever_id_fkey', 'messages', 'readers', ['reciever_id'], ['reader_id'])
    op.drop_table('rooms')
    # ### end Alembic commands ###
