"""added columns first_reader_id and second_reader_id in rooms table

Revision ID: 9a67c8067d0a
Revises: 0180e2da7f53
Create Date: 2022-05-03 22:10:39.964649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a67c8067d0a'
down_revision = '0180e2da7f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('first_reader_id', postgresql.UUID(), nullable=False))
    op.add_column('rooms', sa.Column('second_reader_id', postgresql.UUID(), nullable=False))
    op.create_foreign_key(None, 'rooms', 'readers', ['second_reader_id'], ['reader_id'])
    op.create_foreign_key(None, 'rooms', 'readers', ['first_reader_id'], ['reader_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'second_reader_id')
    op.drop_column('rooms', 'first_reader_id')
    # ### end Alembic commands ###
