"""removed columns author_id and book_id from books_authors

Revision ID: a53316d53b9d
Revises: 279e1bc9bff4
Create Date: 2022-05-06 02:59:43.308799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a53316d53b9d'
down_revision = '279e1bc9bff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_authors_book_id_fkey', 'books_authors', type_='foreignkey')
    op.drop_constraint('books_authors_author_id_fkey', 'books_authors', type_='foreignkey')
    op.drop_column('books_authors', 'book_id')
    op.drop_column('books_authors', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_authors', sa.Column('author_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('books_authors', sa.Column('book_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('books_authors_author_id_fkey', 'books_authors', 'authors', ['author_id'], ['author_id'])
    op.create_foreign_key('books_authors_book_id_fkey', 'books_authors', 'books', ['book_id'], ['book_id'])
    # ### end Alembic commands ###
