"""created books authors and books genres table

Revision ID: ae742e4e7427
Revises: c5a6f1c5ac30
Create Date: 2022-04-28 18:58:47.522623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ae742e4e7427"
down_revision = "c5a6f1c5ac30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books_authors",
        sa.Column("books_authors_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("author_id", postgresql.UUID(), nullable=False),
        sa.Column("book_id", postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.author_id"],
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.book_id"],
        ),
        sa.PrimaryKeyConstraint("books_authors_id"),
    )
    op.create_table(
        "books_genres",
        sa.Column("books_genres_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("genre_id", postgresql.UUID(), nullable=False),
        sa.Column("book_id", postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.book_id"],
        ),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.genre_id"],
        ),
        sa.PrimaryKeyConstraint("books_genres_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books_genres")
    op.drop_table("books_authors")
    # ### end Alembic commands ###
