"""created books table

Revision ID: c5a6f1c5ac30
Revises: d177de2b888c
Create Date: 2022-04-28 15:22:49.246848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c5a6f1c5ac30"
down_revision = "d177de2b888c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("book_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("synopsis", sa.String(), nullable=True),
        sa.Column("edition", sa.String(length=50), nullable=True),
        sa.Column("ISBN", sa.String(length=13), nullable=True),
        sa.Column("publisher", sa.String(length=150), nullable=True),
        sa.Column("cover_img", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("book_id"),
        sa.UniqueConstraint("ISBN"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books")
    # ### end Alembic commands ###
